# Generated by Django 5.2.5 on 2025-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
